void win();
void gameOver();

void win(){
	//prints a victory message
	system("cls");
	textcolor(TGREEN);
	gotoxy(10, 5);	
	printf("	VVVVVVVV           VVVVVVVV iiii                               tttt                                                                      !!! 		 ");
	gotoxy(10, 6);
	printf("	V::::::V           V::::::Vi::::i                           ttt:::t                                                                     !!:!!		 ");
	gotoxy(10, 7);
	printf("	V::::::V           V::::::V iiii                            t:::::t                                                                     !:::!		 ");
	gotoxy(10, 8);
	printf("	V::::::V           V::::::V                                 t:::::t                                                                     !:::!		 ");
	gotoxy(10, 9);
	printf("	 V:::::V           V:::::Viiiiiii     ccccccccccccccccttttttt:::::ttttttt       ooooooooooo   rrrrr   rrrrrrrrryyyyyyy           yyyyyyy!:::!		 ");
	gotoxy(10, 10);
	printf("	  V:::::V         V:::::V i:::::i   cc:::::::::::::::ct:::::::::::::::::t     oo:::::::::::oo r::::rrr:::::::::ry:::::y         y:::::y !:::!		 ");
	gotoxy(10, 11);
	printf("	   V:::::V       V:::::V   i::::i  c:::::::::::::::::ct:::::::::::::::::t    o:::::::::::::::or:::::::::::::::::ry:::::y       y:::::y  !:::!		 ");
	gotoxy(10, 12);
	printf("	    V:::::V     V:::::V    i::::i c:::::::cccccc:::::ctttttt:::::::tttttt    o:::::ooooo:::::orr::::::rrrrr::::::ry:::::y     y:::::y   !:::!		 ");
	gotoxy(10, 13);
	printf("	     V:::::V   V:::::V     i::::i c::::::c     ccccccc      t:::::t          o::::o     o::::o r:::::r     r:::::r y:::::y   y:::::y    !:::!		 ");
	gotoxy(10, 14);					
	printf("	      V:::::V V:::::V      i::::i c:::::c                   t:::::t          o::::o     o::::o r:::::r     rrrrrrr  y:::::y y:::::y     !:::!		 ");
	gotoxy(10, 15);
	printf("	       V:::::V:::::V       i::::i c:::::c                   t:::::t          o::::o     o::::o r:::::r               y:::::y:::::y      !!:!!		 ");
	gotoxy(10, 16);
	printf("	        V:::::::::V        i::::i c::::::c     ccccccc      t:::::t    tttttto::::o     o::::o r:::::r                y:::::::::y        !!! 		 ");
	gotoxy(10, 17);
	printf("	         V:::::::V        i::::::ic:::::::cccccc:::::c      t::::::tttt:::::to:::::ooooo:::::o r:::::r                 y:::::::y             		 ");
	gotoxy(10, 18);
	printf("	          V:::::V         i::::::i c:::::::::::::::::c      tt::::::::::::::to:::::::::::::::o r:::::r                  y:::::y          !!! 		 ");
	gotoxy(10, 19);
	printf("	           V:::V          i::::::i  cc:::::::::::::::c        tt:::::::::::tt oo:::::::::::oo  r:::::r                 y:::::y          !!:!!		 ");
	gotoxy(10, 10);
	printf("	            VVV           iiiiiiii    cccccccccccccccc          ttttttttttt     ooooooooooo    rrrrrrr                y:::::y            !!! 		 ");
	gotoxy(10, 21);
	printf("	                                                                                                                     y:::::y                 		 ");
	gotoxy(10, 22);
	printf("	                                                                                                                    y:::::y                  		 ");
	gotoxy(10, 23);
	printf("	                                                                                                                   y:::::y                   		 ");
	gotoxy(10, 24);
	printf("	                                                                                                                  y:::::y                    		 ");
	gotoxy(10, 25);
	printf("	                                                                                                                 yyyyyyy                     		 ");
	gotoxy(10, 26);		
	printf("           								  Congratulations!       													                                     ");
	getch(); 
	exit(0);
}

void gameOver(){
	//prints the logo of the game and a lose message
	system("cls");
	textcolor(TGREEN);
	gotoxy(10, 10);
	printf(" 		DDDDDDDDDDDDD                                               ffffffffffffffff                                          tttt           !!! 			");
	gotoxy(10, 11);
	printf(" 		D::::::::::::DDD                                           f::::::::::::::::f                                      ttt:::t          !!:!!			");
	gotoxy(10, 12);
	printf(" 		D:::::::::::::::DD                                        f::::::::::::::::::f                                     t:::::t          !:::!			");
	gotoxy(10, 13);
	printf(" 		DDD:::::DDDDD:::::D                                       f::::::fffffff:::::f                                     t:::::t          !:::!			");
	gotoxy(10, 14);	
	printf(" 		  D:::::D    D:::::D     eeeeeeeeeeee    aaaaaaaaaaaaa    f:::::f       ffffffeeeeeeeeeeee    aaaaaaaaaaaaa  ttttttt:::::ttttttt    !:::!			");
	gotoxy(10, 15);
	printf(" 		  D:::::D     D:::::D  ee::::::::::::ee  a::::::::::::a   f:::::f           ee::::::::::::ee  a::::::::::::a t:::::::::::::::::t    !:::!			");
	gotoxy(10, 16);
	printf(" 		  D:::::D     D:::::D e::::::eeeee:::::eeaaaaaaaaa:::::a f:::::::ffffff    e::::::eeeee:::::eeaaaaaaaaa:::::at:::::::::::::::::t    !:::!			");
	gotoxy(10, 17);
	printf(" 		  D:::::D     D:::::De::::::e     e:::::e         a::::a f::::::::::::f   e::::::e     e:::::e         a::::atttttt:::::::tttttt    !:::!			");
	gotoxy(10, 18);
	printf(" 		  D:::::D     D:::::De:::::::eeeee::::::e  aaaaaaa:::::a f::::::::::::f   e:::::::eeeee::::::e  aaaaaaa:::::a      t:::::t          !:::!			");
	gotoxy(10, 19);
	printf(" 		  D:::::D     D:::::De:::::::::::::::::e aa::::::::::::a f:::::::ffffff   e:::::::::::::::::e aa::::::::::::a      t:::::t          !:::!			");
	gotoxy(10, 20);
	printf(" 		  D:::::D     D:::::De::::::eeeeeeeeeee a::::aaaa::::::a  f:::::f         e::::::eeeeeeeeeee a::::aaaa::::::a      t:::::t          !!:!!			");
	gotoxy(10, 21);
	printf(" 		  D:::::D    D:::::D e:::::::e         a::::a    a:::::a  f:::::f         e:::::::e         a::::a    a:::::a      t:::::t    tttttt !!! 			");	
	gotoxy(10, 22);
	printf(" 		DDD:::::DDDDD:::::D  e::::::::e        a::::a    a:::::a f:::::::f        e::::::::e        a::::a    a:::::a      t::::::tttt:::::t     			");
	gotoxy(10, 23);
	printf(" 		D:::::::::::::::DD    e::::::::eeeeeeeea:::::aaaa::::::a f:::::::f         e::::::::eeeeeeeea:::::aaaa::::::a      tt::::::::::::::t !!! 			");
	gotoxy(10, 24);
	printf(" 		D::::::::::::DDD       ee:::::::::::::e a::::::::::aa:::af:::::::f          ee:::::::::::::e a::::::::::aa:::a       tt:::::::::::tt!!:!!			");
	gotoxy(10, 25);
	printf(" 		DDDDDDDDDDDDD            eeeeeeeeeeeeee  aaaaaaaaaa  aaaafffffffff            eeeeeeeeeeeeee  aaaaaaaaaa  aaaa         ttttttttttt   !!! 			");
	gotoxy(10,30);
	printf("                                                               Better Luck Next Time!                                                                       ");
	getch();
	exit(0);
}
