void win();
void gameOver();

void win(){
	//prints a victory message
	system("cls");
	textcolor(TGREEN);
	gotoxy(5, 5);	
	printf("	VVVVVVVV           VVVVVVVV iiii                               tttt                                                                      !!! 		 ");
	gotoxy(5, 6);
	printf("	V::::::V           V::::::Vi::::i                           ttt:::t                                                                     !!:!!		 ");
	gotoxy(5, 7);
	printf("	V::::::V           V::::::V iiii                            t:::::t                                                                     !:::!		 ");
	gotoxy(5, 8);
	printf("	V::::::V           V::::::V                                 t:::::t                                                                     !:::!		 ");
	gotoxy(5, 9);
	printf("	 V:::::V           V:::::Viiiiiii     ccccccccccccccccttttttt:::::ttttttt       ooooooooooo   rrrrr   rrrrrrrrryyyyyyy           yyyyyyy!:::!		 ");
	gotoxy(5, 10);
	printf("	  V:::::V         V:::::V i:::::i   cc:::::::::::::::ct:::::::::::::::::t     oo:::::::::::oo r::::rrr:::::::::ry:::::y         y:::::y !:::!		 ");
	gotoxy(5, 11);
	printf("	   V:::::V       V:::::V   i::::i  c:::::::::::::::::ct:::::::::::::::::t    o:::::::::::::::or:::::::::::::::::ry:::::y       y:::::y  !:::!		 ");
	gotoxy(5, 12);
	printf("	    V:::::V     V:::::V    i::::i c:::::::cccccc:::::ctttttt:::::::tttttt    o:::::ooooo:::::orr::::::rrrrr::::::ry:::::y     y:::::y   !:::!		 ");
	gotoxy(5, 13);
	printf("	     V:::::V   V:::::V     i::::i c::::::c     ccccccc      t:::::t          o::::o     o::::o r:::::r     r:::::r y:::::y   y:::::y    !:::!		 ");
	gotoxy(5, 14);					
	printf("	      V:::::V V:::::V      i::::i c:::::c                   t:::::t          o::::o     o::::o r:::::r     rrrrrrr  y:::::y y:::::y     !:::!		 ");
	gotoxy(5, 15);
	printf("	       V:::::V:::::V       i::::i c:::::c                   t:::::t          o::::o     o::::o r:::::r               y:::::y:::::y      !!:!!		 ");
	gotoxy(5, 16);
	printf("	        V:::::::::V        i::::i c::::::c     ccccccc      t:::::t    tttttto::::o     o::::o r:::::r                y:::::::::y        !!! 		 ");
	gotoxy(5, 17);
	printf("	         V:::::::V        i::::::ic:::::::cccccc:::::c      t::::::tttt:::::to:::::ooooo:::::o r:::::r                 y:::::::y             		 ");
	gotoxy(5, 18);
	printf("	          V:::::V         i::::::i c:::::::::::::::::c      tt::::::::::::::to:::::::::::::::o r:::::r                  y:::::y          !!! 		 ");
	gotoxy(5, 19);
	printf("	           V:::V          i::::::i  cc:::::::::::::::c        tt:::::::::::tt oo:::::::::::oo  r:::::r                 y:::::y          !!:!!		 ");
	gotoxy(5, 20);
	printf("	            VVV           iiiiiiii    cccccccccccccccc          ttttttttttt     ooooooooooo    rrrrrrr                y:::::y            !!! 		 ");
	gotoxy(5, 21);
	printf("	                                                                                                                     y:::::y                 		 ");
	gotoxy(5, 22);
	printf("	                                                                                                                    y:::::y                  		 ");
	gotoxy(5, 23);
	printf("	                                                                                                                   y:::::y                   		 ");
	gotoxy(5, 24);
	printf("	                                                                                                                  y:::::y                    		 ");
	gotoxy(5, 25);
	printf("	                                                                                                                 yyyyyyy                     		 ");
	gotoxy(5, 26);		
	printf("                                                                Congratulations!                       			                                         ");
	getch(); 
	exit(0);
}

void gameOver(){
	//prints the logo of the game and a lose message
	system("cls");
	textcolor(TGREEN);
	gotoxy(15, 10);
	printf("            dddddddd                                                                                                    ");
	gotoxy(15, 11);
	printf("            d::::::d                       ffffffffffffffff                                          tttt           !!! ");
	gotoxy(15, 12);
	printf("            d::::::d                      f::::::::::::::::f                                      ttt:::t          !!:!!");
	gotoxy(15, 13);
	printf("            d::::::d                     f::::::::::::::::::f                                     t:::::t          !:::!");
	gotoxy(15, 14);	
	printf("            d:::::d                      f::::::fffffff:::::f                                     t:::::t          !:::!");
	gotoxy(15, 15);
	printf("    ddddddddd:::::d     eeeeeeeeeeee     f:::::f       ffffffeeeeeeeeeeee    aaaaaaaaaaaaa  ttttttt:::::ttttttt    !:::!");
	gotoxy(15, 16);
	printf("  dd::::::::::::::d   ee::::::::::::ee   f:::::f           ee::::::::::::ee  a::::::::::::a t:::::::::::::::::t    !:::!");
	gotoxy(15, 17);
	printf(" d::::::::::::::::d  e::::::eeeee:::::eef:::::::ffffff    e::::::eeeee:::::eeaaaaaaaaa:::::at:::::::::::::::::t    !:::!");
	gotoxy(15, 18);
	printf("d:::::::ddddd:::::d e::::::e     e:::::ef::::::::::::f   e::::::e     e:::::e         a::::atttttt:::::::tttttt    !:::!");
	gotoxy(15, 19);
	printf("d::::::d    d:::::d e:::::::eeeee::::::ef::::::::::::f   e:::::::eeeee::::::e  aaaaaaa:::::a      t:::::t          !:::!");
	gotoxy(15, 20);
	printf("d:::::d     d:::::d e:::::::::::::::::e f:::::::ffffff   e:::::::::::::::::e aa::::::::::::a      t:::::t          !:::!");
	gotoxy(15, 21);
	printf("d:::::d     d:::::d e::::::eeeeeeeeeee   f:::::f         e::::::eeeeeeeeeee a::::aaaa::::::a      t:::::t          !!:!!");	
	gotoxy(15, 22);
	printf("d:::::d     d:::::d e:::::::e            f:::::f         e:::::::e         a::::a    a:::::a      t:::::t    tttttt !!! ");
	gotoxy(15, 23);
	printf("d::::::ddddd::::::dde::::::::e          f:::::::f        e::::::::e        a::::a    a:::::a      t::::::tttt:::::t     ");
	gotoxy(15, 24);
	printf(" d:::::::::::::::::d e::::::::eeeeeeee  f:::::::f         e::::::::eeeeeeeea:::::aaaa::::::a      tt::::::::::::::t !!! ");
	gotoxy(15, 25);
	printf("  d:::::::::ddd::::d  ee:::::::::::::e  f:::::::f          ee:::::::::::::e a::::::::::aa:::a       tt:::::::::::tt!!:!!");
	gotoxy(15, 26);
	printf("   ddddddddd   ddddd    eeeeeeeeeeeeee  fffffffff            eeeeeeeeeeeeee  aaaaaaaaaa  aaaa         ttttttttttt   !!! ");
	gotoxy(15,30);
	printf("                                                  Better Luck Next Time!                                                ");
	getch();
	exit(0);
}
